### ISSUE TITLE
Switching ON/OFF not detected

### ISSUE THREAD

**Issue by KoenHak** [m4recek/panasonic-viera-remote-control#1]
When using the plugin with Homey, the On/Off status is not properly broadcasted, which means Homey does not detect if the TV is switched on or off via the remote control, which results in the fact a trigger for Homey can't be set. 

Using a Panasonic 58DX700 series.

**Comment by m4recek** [comment]
I have not created Homey integration, you are most likely commenting in the wrong repository.
